import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { formatLargeNumber } from 'src/app/utils/valueManipulation';

@Component({
  selector: 'app-stock-key-metrics',
  templateUrl: './stock-key-metrics.component.html',
  styleUrls: ['./stock-key-metrics.component.css']
})
export class StockKeyMetricsComponent {
  constructor() {}

  @Input() stockName: string = ''
  @Input() fiscalYears: string[] = []
  @Input() allMetrics: any[][] = []
  @Input() profitable: boolean = false
  @Input() growingRevenue: boolean = false

  displayedMetric: string = 'Total Revenue'
  displayedDefinition: string = 'A key financial metric that indicates the overall income generated by the company before deducting any expenses, taxes, or interest. This is the best metric to determine if a companies core product sales are growing or shrinking.'

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['stockName'].previousValue != undefined && changes['stockName']?.currentValue != changes['stockName']?.previousValue) {
      this.stockName = changes['stockName']?.currentValue;
      this.fiscalYears = changes['fiscalYears']?.currentValue;
      this.allMetrics = changes['allMetrics']?.currentValue;
      this.profitable = changes['profitable']?.currentValue;
      this.growingRevenue = changes['growingRevenue']?.currentValue;
    }
  }

  renderDefinition(metric: string) {
    let metricToDefine = metric

    switch (metricToDefine) {
      case 'Total Revenue':
        this.displayedMetric = 'Total Revenue'
        this.displayedDefinition = 'A key financial metric that indicates the overall income generated by the company before deducting any expenses, taxes, or interest. This is the best metric to determine if a companies core product sales are growing or shrinking.'
        break
      case 'Total Assets':
        this.displayedMetric = 'Total Assets'
        this.displayedDefinition = 'A key financial metric that indicates the total value of all assets owned by the company. For mature companies this metric is great for evaluating the companies ability to weather a storm, but for young fast growing companies this metric is generally not as useful.'
        break
      case 'Total Liabilities':
        this.displayedMetric = 'Total Liabilities'
        this.displayedDefinition = 'A key financial metric that indicates the total value of all liabilities owed by the company. For mature companies this metric should be low relative to the companies assets, at young unprofitable companies it generally looks worse than it is, unless the company has lost the ability to generate funding.'
        break
      case 'Net Income':
        this.displayedMetric = 'Net Income'
        this.displayedDefinition = 'A key financial metric that indicates the total income generated by the company after deducting all expenses, taxes, and interest. This metric is a concise way to determine profitability, and when compared with revenue, how much of revenue becomes profit.'
        break
      case 'Total Shareholder Equity':
        this.displayedMetric = 'Total Shareholder Equity'
        this.displayedDefinition = 'A key financial metric that indicates the total value of all shareholder equity. This metric is useful for determining how much of the companies assets are owned by shareholders, and how much is owned by debtors.'
        break
      case 'Operating Cashflow':
        this.displayedMetric = 'Operating Cashflow'
        this.displayedDefinition = 'A key financial metric that indicates the total cash generated by the company from its core business operations, so it excludes financing and investing activities.'
        break
      case 'Free Cashflow':
        this.displayedMetric = 'Free Cashflow'
        this.displayedDefinition = 'This metric is the operating cash flow with capital expenditures subtracted, and is a great metric for determining how much cash the company has to invest in growth, pay dividends, or pay down debt.'
        break
      case 'Capital Expenditures':
        this.displayedMetric = 'Capital Expenditures'
        this.displayedDefinition = 'A key financial metric that indicates the total amount of money used to purchase long term assets, such as property, plant, and equipment. This metric is useful for determining how much money the company is investing in itself.'
        break
      case 'Gross Profit Margin':
        this.displayedMetric = 'Gross Profit Margin'
        this.displayedDefinition = 'A key financial metric that indicates the percentage of revenue that becomes gross profit without accounting for operational expenses.'
        break
      case 'Operating Income Margin':
        this.displayedMetric = 'Operating Income Margin'
        this.displayedDefinition = 'A key financial metric that indicates the percentage of revenue that becomes operating income by subtracting all expenses except interest paid and taxes.'
        break
      case 'Total Debt':
        this.displayedMetric = 'Total Debt'
        this.displayedDefinition = 'Includes all forms of debt obligations, such as loans, bonds, credit lines, and other borrowed funds that the company is obligated to repay within a specified time frame. A negative value here means that the company has more cash/liquidity than debt.'
        break
      default :
        break
    }
  }
}
